// <auto-generated />
using EventEase.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventEase.Migrations
{
    [DbContext(typeof(EventEaseContext))]
    [Migration("20260612203000_SeedSouthAfricanTestData")]
    partial class SeedSouthAfricanTestData
    {
    }
}
